### ISSUE TITLE
ユースケースにログイン、ログアウトを追加する

### ISSUE THREAD

**Issue by Cyberdrgn** [kbc-itw/BookChain#2]
## 概要

当初の想定漏れにより現在作成できていない、
ログイン・ログアウトのユースケース記述を追加する。

## 目的

ユースケースを明確にし、以降の設計の基準とする。

## タスク

- [x] ユースケース：ログインの作成
- [x] ユースケース：ログアウトの作成
- [x] 各ユースケースのレビュー

**Comment by Huruikagi** [comment]
今回必要な分は完了したっぽい
