### ISSUE TITLE
KotlinがFablic Java SDKを正常に使用できるか調査

### ISSUE THREAD

**Issue by nakamuratomohiko** [kbc-itw/BookChain#22]
## 概要 
Kotlinでのサーバサイド開発を検討しています。そのためにFablic JavaSDKを正常に使用できるかの調査する。
## 目的
Kotlinでサーバサイドの開発をするための調査

**Comment by Huruikagi** [comment]
https://github.com/hyperledger/fabric-sdk-java

**Comment by Huruikagi** [comment]
今回のプロジェクトでは、JavaではなくNode SDKを利用することになった。
