### ISSUE TITLE
所持本を登録していないユーザの対応

### ISSUE THREAD

**Issue by Cyberdrgn** [kbc-itw/BookChain#28]
## 概要 

[ユースケース：貸し借り状況の確認](
https://github.com/kbc-itw/BookChain/wiki/%E3%83%A6%E3%83%BC%E3%82%B9%E3%82%B1%E3%83%BC%E3%82%B9%EF%BC%9A%E8%B2%B8%E3%81%97%E5%80%9F%E3%82%8A%E7%8A%B6%E6%B3%81%E3%81%AE%E7%A2%BA%E8%AA%8D)
<br>
このユースケースでは所持本を登録していないユーザは貸し借り状況の確認ができなくなっている。
<br>
所持本を登録していなくても貸し借りができるようにするのかどうか
<br>

## 目的

所持本を登録していないユーザの対応を決める

**Comment by Huruikagi** [comment]
これ所持本登録してないけど借りてるだけのパターンも4.1でカバーできない？

**Comment by Cyberdrgn** [comment]
4.1でカバーするようにして
4.3と3.5.2を消しました。
