### ISSUE TITLE
gitで特定のCommitLevelに変更できない問題

### ISSUE THREAD

**Issue by nakamuratomohiko** [kbc-itw/BookChain#30]
## 概要 
hyper...fabric-sdk-javaのversionをv1.0.1での開発をする際にFabricとFabric-caは特定のCommit levelの状態を使用しないと動作保証がない。Fabricの方はエラーなく特定のCommit levelに変更できたがFabric-caに問題が発生して変更できない状態になる。
## 目的
Fabric-caを特定のCommit levelに変更したい。
git reset --hard bc2b642f4a9ef2dcb393bf7da512ce43e1ec1a68

## 手順
git clone  https://github.com/hyperledger/fabric-ca.git
git reset --hard bc2b642f4a9ef2dcb393bf7da512ce43e1ec1a68

**Comment by nakamuratomohiko** [comment]
とりあえずfabtic-ca-1.0.1のリリースを使用する

**Comment by Huruikagi** [comment]
リリースを使うので必要がない
