### ISSUE TITLE
sdk-javav1.0.1の足りないJARを追加してもコンパイルエラーが起こる

### ISSUE THREAD

**Issue by nakamuratomohiko** [kbc-itw/BookChain#31]
## 概要 
sdk-javaには足りないJARがあり、ダウンロードして手動で追加したのだがコンパイルエラーが発生する。
ダウンロードする前のサイトには必要なメソッドがファイル書いてあるが手動で入れたクラスにはそのメソッドがない状態になっている。
versionはv1.0.1であっているためミスではない
## 目的
コンパイルエラーを発生させない

**Comment by Huruikagi** [comment]
これ君mavenかgradle経由でインストールしてないから依存関係解決できてないんじゃない？

**Comment by nakamuratomohiko** [comment]
gradle経由で解決
