### ISSUE TITLE
Wiki記載のFQDNのDefinitionは正規表現として不正である

### ISSUE THREAD

**Issue by wamekukyouzin** [kbc-itw/BookChain#44]
[See](https://github.com/kbc-itw/BookChain/wiki/Data-Model#definition-10)

どこがあかんのか分からんが正しい正規表現になっていない
あとこの定義だとlocalhostが通らなそうな気がするのでつらあじ

**Comment by Huruikagi** [comment]
なんかいいの探してくれ

**Comment by wamekukyouzin** [comment]
RFC準拠って明記してあるのが[これ](https://github.com/emilbayes/is-domain-name)くらいだったのでこれ使うよ
