### ISSUE TITLE
ロギングライブラリの導入

### ISSUE THREAD

**Issue by Huruikagi** [kbc-itw/BookChain#47]
## 概要

winstonでもlog4jsでもなんでもよいので、ロギングライブラリを導入して利用するようにする。

## 目的

こういうのは導入が遅いほどダメージがでかい。
とりあえず導入して、ロガー経由でコンソールにログはくようにしておいたら、
後からファイルに吐き出すようにするのとかは割合容易にできる。
また、ログレベルをきちんと使い分けていれば、デバッグ用ログとかもいちいち消さなくても書きっぱなしでいいので色々楽。
（もちろんある程度の方針は必要だが）

## タスク

- [x] 利用するライブラリの選定
- [ ] 既存のコードの中で利用するべきところで利用

## 備考

expressのmorganミドルウェアはHTTP(S)リクエストのアクセスログとかを残すものであって、ここで入れて欲しいっていってるものじゃないよ。console.log的に使うものじゃないよ。でもそれはそれで入れておいたほうが良い気はする。

**Comment by wamekukyouzin** [comment]
winstonは2.x->3.x系列に変わる直前のようなのでlog4jsにしておく
