### ISSUE TITLE
ChaincodeのcreateRoomの戻り値にInviteTokenが含まれていない

### ISSUE THREAD

**Issue by wamekukyouzin** [kbc-itw/BookChain#54]
[これ](https://github.com/kbc-itw/BookChain/wiki/Chaincode-Room#createroom)

**Comment by Huruikagi** [comment]
これはチェーンコード側で生成するべきではない。
チェーンコードは、検証のために複数のピアで平行して実行され、同一の結果となることが期待される。
そのため、ランダム生成やタイムスタンプ付与のような実行するタイミングによって異なる結果を生むような処理を行えないし、行うべきではない。
また、逆に、推測可能でどのピアで実行しても同じトークンを生成するようにするのであれば、トークンとして意味がないので、これまた不適切である。

以上の理由から、アプリケーションサーバプログラム側でトークンを生成するべきであり、このトークンはチェーンコードネットワーク内に流さない私用とした。

**Comment by wamekukyouzin** [comment]
ということなので、InviteTokenについては「RestAPIのcreateRoomにおいてChaincode側から部屋情報を拾ってきたあとにUUIDを生成する」ことで解決することとした
