### ISSUE TITLE
WebSocketを用いる一連の貸し借り処理が正常に動作するようにする

### ISSUE THREAD

**Issue by wamekukyouzin** [kbc-itw/BookChain#57]
クライアントと一緒に一連の流れが正しく（非正常系も含めて）行えるようにしてくれるとうれしいな 🍣 
サーバサイドはWebSocketRoom、クライアントサイドはTradeGuestComponentならびにTradeInviterComponentが関連する

**Comment by nakamuratomohiko** [comment]
![basyauma](https://user-images.githubusercontent.com/20035879/35025379-854f183c-fb88-11e7-9ece-3dc35cbb007e.jpg)

**Comment by wamekukyouzin** [comment]
bootstrapでroom用のルータとwebsocket用のルータを登録する必要がある。
chaincodeへのアクセス用関数を登録する必要があるが、websocketの動作確認をするためであればダミー関数を渡したほうが無難だと思う。
